// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RelayState struct {
	Singleton bool
	Epoch     int64
	Clock     pgtype.Timestamptz
	Data      []byte
}
