// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relay.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockRelay = `-- name: LockRelay :one
SELECT epoch, clock, data, clock_timestamp()::timestamptz AS now FROM relay_state WHERE singleton = true FOR UPDATE
`

type LockRelayRow struct {
	Epoch int64
	Clock pgtype.Timestamptz
	Data  []byte
	Now   pgtype.Timestamptz
}

func (q *Queries) LockRelay(ctx context.Context) (LockRelayRow, error) {
	row := q.db.QueryRow(ctx, lockRelay)
	var i LockRelayRow
	err := row.Scan(
		&i.Epoch,
		&i.Clock,
		&i.Data,
		&i.Now,
	)
	return i, err
}

const saveRelay = `-- name: SaveRelay :execrows
UPDATE relay_state SET data = $1, epoch = epoch + 1, clock = $2
WHERE singleton = true AND epoch = $3
`

type SaveRelayParams struct {
	Data  []byte
	Clock pgtype.Timestamptz
	Epoch int64
}

func (q *Queries) SaveRelay(ctx context.Context, arg SaveRelayParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveRelay, arg.Data, arg.Clock, arg.Epoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
